### ISSUE TITLE
Delete when processed throws  Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by cocoonkid** [soberhacker/obsidian-telegram-sync#108]
When I disable it and just "mark as processed" it works.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/43231640/511b066e-2750-441f-8111-bafbebdd64da)

Thanks so much! This is really helpful!

**Comment by soberhacker** [comment]
Hi @cocoonkid!
Thanks for using the plugin.

Unfortunatelly I can't repeat the error. So I need to ask you some additional questions, to clarify the details:
1. Have you tried to restart Obsidian and turn on again the option "Delete messages from Telegram"?  After this does error still exist?
2. Do you use the last release 1.5.0?
3. The error typically arises when it is trying to perform an operation intended for a file but instead it is a directory.  Could you send me your settings? (do not send your bot token)

Best Regards, soberHacker

**Comment by cocoonkid** [comment]
@soberhacker 

Yes, 1.5

Starting Obisidan fresh and then enabling  the plugin made it work!

Thanks :)

**Comment by soberhacker** [comment]
> @soberhacker 
> 
> Yes, 1.5
> 
> Starting Obisidan fresh and then enabling  the plugin made it work!
> 
> Thanks :)
> 
> 
Cool! Sorry for the many questions, but I need to ask the last one :) Have you switched off and then on the plugin after copying new release in the plugin directory or tried immediately?  You are not the first one, who had a similar problem. Maybe your answer will help me to repeat  the error on my laptop. Thanks

**Comment by cocoonkid** [comment]
Shoot as many as you want :)

I tried immediately. 

so:

1. Installed Plugin manually by creating the folder telegram-sync in my .obsidian/plugins folder.
2. Downloaded and moved the three files to the folder.
4. DID NOT RESTART  Obsidian (I just noticed your manual makes the restart explicit) and enabled Telegram Sync in Community plugins.
5.  Did all the bot steps.
6. Encountered the error.


Hope that helps.

**Comment by cocoonkid** [comment]
Now I have a question. :)

Would it be possible to designate a second device ID as fallback?
If that might make basic sense I'd open a separate features request for this. Mainly it's about having my laptop as fallback when traveling since currently my desktop is the designated main ID. But when I travel then the Desktop is shutdown.

**Comment by cocoonkid** [comment]
I found another small Issue but rather an UX issue.
When the plugin is working properly from the get go it will delete all processed messages which is good.
But when the channel is empty it will be removed from visibility other devices (on android at least). EVEN WHEN PINNED!
Telegram Desktop keeps it without problem.

I suggest adding some placeholder value or even better add a whitelist so I can for example add "Init" as a word that will never be processed if found alone.

**Comment by soberhacker** [comment]
> Now I have a question. :)
> 
> Would it be possible to designate a second device ID as fallback?
> If that might make basic sense I'd open a separate features request for this. Mainly it's about having my laptop as fallback when traveling since currently my desktop is the designated main ID. But when I travel then the Desktop is shutdown.

Questions are better than bugs :)

When you travel just empty the field with device id on laptop and plugin will receive  data again. When you come back to your desktop, just enter the main id again.

**Comment by cocoonkid** [comment]
Thanks :)

**Comment by congkai88** [comment]
I got the same issue too. However i notice if "Template file location" is empty, it will have this error.
so i followed https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md to make a template.md and point  "Template file location" to it. seems working after that. just noting it here. :)
