### ISSUE TITLE
UX Issue - "empty" bot chats disappear when using multiple devices or restarting desktop. Even when pinned!

### ISSUE THREAD

**Issue by cocoonkid** [soberhacker/obsidian-telegram-sync#109]
I found another small Issue but rather an UX issue.
When the plugin is working properly from the get go it will delete all processed messages which is good.
But when the channel is empty it will be removed from visibility other devices (on android at least). Even when PINNED!
Telegram Desktop keeps it without problem when empty and pinned.

I suggest adding some placeholder value or even better add a whitelist so I can for example add "Init" as a word that will never be processed if found alone.

_Originally posted by @cocoonkid in https://github.com/soberhacker/obsidian-telegram-sync/issues/108#issuecomment-1567155033_

I confirmed this behaviour over multiple days now.
one single whitelisted word to act as "permanent sticky header" would greatly improve the UX.

**Comment by soberhacker** [comment]
Hi! Thanks for separate issue!
I want to clarify which kinds of chats have this issue: personal chat with a bot, channel or group?

Best Regards, soberhacker

**Comment by cocoonkid** [comment]
Personal chat with the bot. Yes.

**Comment by soberhacker** [comment]
Done
https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.6.0
