### ISSUE TITLE
Append to existing notes

### ISSUE THREAD

**Issue by congkai88** [soberhacker/obsidian-telegram-sync#110]
It would be great if we could use append to existing notes if found. 

This is in used with Periodic Notes where we use it as journal entry to the day's notes. Sometimes we can log down events and journals from telegram and it can be appended to the date. 

I noted we can create new file to the date through file patch variable, but if the date file exist, it will create another unique file. This might not work with Periodic notes. So the append function will work if file path is done. (The file path has not been implemented. )

And for now, if i do not use "append all to Telegram.md" it creates a new file as "content - 20230601165626000. "

**Comment by soberhacker** [comment]
Release version 2.0.0 already published
