### ISSUE TITLE
Change Title of new Notes

### ISSUE THREAD

**Issue by muejam09** [soberhacker/obsidian-telegram-sync#127]
Is there a possibility to change the default title of newly created notes? If not, that would be a very nice feature. 

For example, a field in the settings where it is possible to state something like 

{{content:firstline}} {{creationDate:YYYY-MM-DD}}

**Comment by soberhacker** [comment]
Hi! I described how it will be done in file [Template Variables List](https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md).
I think 3 or 4 weeks and it will be implemented.

**Comment by soberhacker** [comment]
Hi @muejam09, you can now test the new beta release [2.0.0-beta.1](https://t.me/obsidian_telegram_sync_insider/16).

You have two ways to install it:
1. Manually, using the link above from our Telegram channel.
2. Directly from the plugin settings, via a special button. This button is only available if you're connected to Telegram as a user and are using a plugin version greater than 1.10.0.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/99afa579-888c-4e1d-ab3d-83e4407e3a44)

**Comment by muejam09** [comment]
Hi!
Thanks for informing me! I just downloaded it and will try it, but fyi: I did not see the button in the Settings and my Plugin version is 1.10.0 and Obsidian is on v1.4.12. I even restarted Obsidian and it did not appear.

**Comment by muejam09** [comment]
Pardon me. My mistake. I did not read the instructions carfeully enough. I am not connected with a Telegram user. Sry for the inconvinience

**Comment by soberhacker** [comment]
Release version 2.0.0 already published
