### ISSUE TITLE
Notes transfer from telegram group

### ISSUE THREAD

**Issue by Gourav1910** [soberhacker/obsidian-telegram-sync#129]
Hi thanks for this amazing plugin. Because of obsidian takes too much time to start it was not efficient to capture our random thoughts fast in obsidian so I created various groups in telegram topic wise. I am the only member of those private groups. Is there any way I can transfer those notes inside obsidian. Even it is ok for me if all the notes of one group stored in one md note. Thankyou so much😊.

**Comment by soberhacker** [comment]
Hi! I described how it will be done in file [Template Variables List](https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md).
I think 3 or 4 weeks and it will be implemented.

Exemplary flow:
1. Add your bot to the group
2. Make it as admin
3. Configure notes path in plugin settings (not implemented)
4. Forward all messages to the same place where they were
5. Bot handle all forwarded messages and create notes in the destination that you point out (step 3)

**Comment by Gourav1910** [comment]
> Hi! I described how it will be done in file [Template Variables List](https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md). I think 3 or 4 weeks and it will be implemented.
> 
> Exemplary flow:
> 
> 1. Add your bot to the group
> 2. Make it as admin
> 3. Configure notes path in plugin settings (not implemented)
> 4. Forward all messages to the same place where they were
> 5. Bot handle all forwarded messages and create notes in the destination that you point out (step 3)

hey thanks for reply. By term "not implemented" did you mean that this feature can't work right now because it is under development but it will work in future?

**Comment by soberhacker** [comment]
"not implemented" has a wider meaning.
Some features are under development, some features will be next after current development, and some features have no schedule at the moment. The state depends on user activity, my and their needs and of course, my free time.

As I wrote before, the feature that will help you to create folders by message topics will be implemented in the nearest feature.

**Comment by soberhacker** [comment]
You can now test the new beta release [2.0.0-beta.1](https://t.me/obsidian_telegram_sync_insider/16).

You have two ways to install it:
1. Manually, using the link above from our Telegram channel.
2. Directly from the plugin settings, via a special button. This button is only available if you're connected to Telegram as a user and are using a plugin version greater than 1.10.0.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/99afa579-888c-4e1d-ab3d-83e4407e3a44)

**Comment by soberhacker** [comment]
Release version 2.0.0 already published
