### ISSUE TITLE
Append new msg at the top of telegram.md

### ISSUE THREAD

**Issue by Gourav1910** [soberhacker/obsidian-telegram-sync#130]
So whenever we send msg it append to the bottom of the telegram.md note and the more we send the msg to our bot the bigger the telegram.md note becomes and hence whenever we open it we got to scroll a lot to view our newer notes. So is it possible that new msgs append at the top of the telegram.md note. It would be more helpful. Thanksz.

**Comment by soberhacker** [comment]
Hi, I am not sure that I will do like you ask. But I think you will have possibility to make ordering using [Template Variables](https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md).
For example, you can put every message to some specified folders and separate notes with file names which start with datetime and sort them using Obsidian interface.
Or maybe I will add some special template variable, to realize the sorting (less likely).

**Comment by soberhacker** [comment]
You can also use keyboard shortcut "ctrl + end" / "cmd + end" to go to the end of file to not scroll at all.
And also I think that it is a bad idea adding everything to the one file, if you are going to work with it regularly in the future.

**Comment by soberhacker** [comment]
Changing messages appending order is available in TS 2.1.0-beta.1 -> https://t.me/c/1913400014/26

**Comment by soberhacker** [comment]
Released in 2.1.0 production release
