### ISSUE TITLE
Relative paths not obeyed

### ISSUE THREAD

**Issue by spiritualgeek** [soberhacker/obsidian-telegram-sync#132]
If you have relative paths switched on in your vault, then this breaks by writing out the full path to an image/file

**Comment by soberhacker** [comment]
Hi
Could you please give me an example? Because I haven't understood everything.
What Obsidian setting did you mean? New link format? What's the value? What path is wrong?

**Comment by spiritualgeek** [comment]
![95946](https://github.com/soberhacker/obsidian-telegram-sync/assets/53917562/752d3de5-89f8-444f-b571-9c2921c3b6f8)

Your plugin places the full path to the file in the markdown link instead

**Comment by soberhacker** [comment]
> ![95946](https://user-images.githubusercontent.com/53917562/248449002-752d3de5-89f8-444f-b571-9c2921c3b6f8.png)
> 
> Your plugin places the full path to the file in the markdown link instead

Show me also,  please,  an example of the path that exists and of the path that you want to get.

Am I right, you need relative paths for some external use? Because Obsidian can parse(open, attach...) any type of paths regardless of  "New link format" value.

**Comment by soberhacker** [comment]
Done in release 1.7.1

**Comment by mnaoumov** [comment]
Nope, not done in release 1.7.1

File added to `photos/file.jpg` and link is added as `![](file.jpg)` instead of `![](photos/file.jpg)`

**Comment by soberhacker** [comment]
> Nope, not done in release 1.7.1
> 
> File added to `photos/file.jpg` and link is added as `![](file.jpg)` instead of `![](photos/file.jpg)`

The behavior you're experiencing is normal when "New link format" is set to "shortest path when possible". If you'd like to see something like `![](photos/file.jpg)`, you'll need to change it to "relative path to file"

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/e3b947ee-7c44-4ccc-a17e-637abbd1339a)

**Comment by mnaoumov** [comment]
@soberhacker and I have `Relative path to file` setting set. My PR make correct link for all kinds of that setting
