### ISSUE TITLE
How can I remove "Forwarded from ******"

### ISSUE THREAD

**Issue by x4IPx** [soberhacker/obsidian-telegram-sync#148]
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/58852253/a15a6da1-d395-4350-b341-d180a30c1cc1)

Не понимаю как убрать поле "Forwarded from ******". 
Не уверен, но она появилось после последнего обновления (1.7.0).
____
I do not understand how to remove the "Forwarded from ******" field.
I'm not sure, but it appeared after the last update (1.7.0).

**Comment by soberhacker** [comment]
Приветствую.
Замени {{content}} на {{content:text}}
В доке мож детально посмотреть
https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/a737ff4a-7025-4c04-8f2e-363a428cfd43)

**Comment by soberhacker** [comment]
Или если ты и файлы пересылаешь, то вот так будет лучше
{{file}}
{{content:text}}
