### ISSUE TITLE
Bot got disconnected all of a sudden

### ISSUE THREAD

**Issue by saeedesmaili** [soberhacker/obsidian-telegram-sync#149]
Hey
Thanks for this useful plugin. I started using it a few days ago. I set up the bot on Telegram and sent some test messages to confirm it's working. I continued using it for a few days and everything was fine.
Then when I sent a message to Bot I didn't get the green checkmark reply yesterday, I thought that was because my obsidian doesn't have internet access at the moment. But I didn't get any confirmation replies from the bot afterward, and when I double-checked the plugin's settings, the "Bot (required)" field was showing "disconnected", while it had the bot token and username available. I tried to connect it again and was successful, but I'm not sure if it will be disconnected afterward or not.

- I'm concerned that the plugin doesn't have a consistent connection with Telegram.
- It doesn't notify me when the connection has been disconnected for some reason.
- It doesn't sync the message I sent to the bot when the connection was disconnected, so I need to re-send those messages.

These make the plugin unreliable, while the main point of using it is to assure me I have a reliable way of sending my thoughts and notes in obsidian when I don't have access to it.

**Comment by soberhacker** [comment]
Hi!
Thanks for your report. I will check.
Could you, please, send a screen of your settings (just the main page)? And if you use a template, then also send the template content.

**Comment by saeedesmaili** [comment]
Here is a screenshot of the settings page, but note that:
- The `Bot (required)` field was disconnected and I connected it again.
- I wasn't using any templates when this happened.

<img width="828" alt="image" src="https://github.com/soberhacker/obsidian-telegram-sync/assets/13351748/5d4b5a1f-6696-4fff-a11a-250ee6462b43">

**Comment by saeedesmaili** [comment]
It is disconnected all of a sudden again
<img width="833" alt="image" src="https://github.com/soberhacker/obsidian-telegram-sync/assets/13351748/edb57a51-59cc-4b4b-9ab9-436383115f7f">

**Comment by saeedesmaili** [comment]
No, when it's disconnected the messages don't sync and I don't even get the green checkmark reply in the bot.
If it helps with debugging, I'm using icloud to sync my obsidian folder (notes and obsidian config folder) between two MacBooks and one iPad, but not sure if this can cause any problem, since the settings of the other plugins that I use are persistent and don't suddenly change like this.

**Comment by saeedesmaili** [comment]
Can I any further help with debugging this? It gets disconnected every few days, and I'm just giving up on it as it's not reliable enough and causes more trouble than benefit with this issue.

**Comment by soberhacker** [comment]
Hi, yes of course. You can find a version 1.8.0.beta in this channel https://t.me/obsidian_telegram_sync_insider
This bug should be resolved there.

**Comment by soberhacker** [comment]
version 1.8.0 is already released. You can update it directly from obsidian

**Comment by saeedesmaili** [comment]
Awesome thank you!
