### ISSUE TITLE
Request: template variable for "text without first line"

### ISSUE THREAD

**Issue by saeedesmaili** [soberhacker/obsidian-telegram-sync#150]
The [template variables](https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md) are very useful. I'm using `## {{content:firstLine}}` to add a title to the text, but I wish there was a complimentary variable like `{{content:textExceptFirstLine}}` to use after the title. This would help with having the title and the rest of the text in a single message.

**Comment by soberhacker** [comment]
Try last release 1.8.0
It has variable {{content:noFirstLine}}
