### ISSUE TITLE
{{creationTime:HH:mm:ss}} - offline messages not coming

### ISSUE THREAD

**Issue by x4IPx** [soberhacker/obsidian-telegram-sync#151]
If the template uses {{creationTime:HH:mm:ss}} and Obsidian is off when the message is sent, the message is not delivered.
____
Если в шаблоне используется {{creationTime:HH:mm:ss}} и в момент отправки сообщения Obsidian был выключен, сообщение не доставляется.

**Comment by soberhacker** [comment]
Приветствую
Не получилось повторить ошибку
Возможно это было из-за ограничения бота в получение сообщений через 24 часа.
Т.е. если запуск обсидиан был через 24 часа после отправки сообщения, то оно не будет получено.

**Comment by x4IPx** [comment]
https://youtu.be/Jm4T87OXpqA

**Comment by x4IPx** [comment]
Но один раз сообщения  пришли с {{creationTime:HH:mm:ss}} в Офлайне.  Пока не знаю почему. Позже ещё раз протестирую ...

**Comment by soberhacker** [comment]
Попробуй версию 1.8.0
Здесь уже не должно быть этой проблемы
