### ISSUE TITLE
Group or chat name without link

### ISSUE THREAD

**Issue by Gourav1910** [soberhacker/obsidian-telegram-sync#152]
Hi so nice to see that finally chat or group name is available in template variable. I was thinking of using those variable as dataview field values but dataview is not supporting the links. So it would be nice update if you bring a template variable in which simply chat or group name render as a plain text. As you can see in the below screenshot "source" is my dataview variable but on querying it is not picking the  source with link. I planned to write queries which would be filter by chat or group name so it would be easier to manage notes coming from various groups of telegram.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/101202140/5800199e-d1b9-4a3b-b251-ff44da792806)

**Comment by soberhacker** [comment]
For filtering, you can use the {{chatId}} variable or filter by `Sorce = "[your](link)"` or perhaps something like `contains("Source:: [NAME]")`. I think you need to delve deeper into the capabilities of DataView.

**Comment by soberhacker** [comment]
This has already been implemented in the latest beta version. You can download it for testing in the Telegram channel -> https://t.me/obsidian_telegram_sync_insider/8

**Comment by soberhacker** [comment]
Done in official release 1.9.0
