### ISSUE TITLE
Not bringing image together with the text note

### ISSUE THREAD

**Issue by Gourav1910** [soberhacker/obsidian-telegram-sync#155]
Hi, I just found out that it is not bringing the image and the text which is associated with the note(not reply text/msg but the msg with the image) is not bringing in one note inside obsidian. I want it to bring both the thing together only then the image will be in context. You should add a embedded link of image above the text so that image will be together with the text.

**Comment by soberhacker** [comment]
Hi
Please, send me a screenshot of the message and a screenshot of the plugin settings and a note content template (if you use).

You can also try this template vaiables:
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/46ec1a8e-4f89-41bf-994b-c6e55175917a)
If Note Content Template is unspecified, template by default will be equal {{content}}
More about templates you can read here -> https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md

**Comment by Gourav1910** [comment]
> 

Hi, yes you are right, in my template I was using the "{{content:text}}" that's why it was bringing text only. But I have one more issue.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/101202140/31f97bdb-a7ca-4122-a3fb-c293c21a9e00)

So i sent this msg to my bot and in obsidian note it only attached one image inside the note and second image is just seperate. So may be you have not implemented this yet but it should bring all the files inside the note. 

This is my template.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/101202140/cdc276c8-6060-4485-a64f-8236f9107ace)

**Comment by Gourav1910** [comment]
And I was also thinking about, if possible I even want follow up msg and files to be append in the existing note if we reply to any previous msg. 

So suppose previous msg which is now synced inside obsidian as a note has id 100 and then few days later suppose if I write a msg(or send a file) which has id 125 but I write it in reply to msg which has id 100 so now this new msg should not be synced as new note(or atleast have a toggle option in settings) but it should be append downside of that note which has id 100 because our new msg is in context to that previous msg. 

I really don't know how coding works so I have no idea how hard or easy it is to implement this feature but I think this should be the next step for this plugin to become even more powerful. So if possible please also consider this feature.

**Comment by soberhacker** [comment]
I hope I have fixed this, try in the last prerelease [1.10.0.Beta](https://t.me/obsidian_telegram_sync_insider/12)
