### ISSUE TITLE
"undefined" added to the content after sync

### ISSUE THREAD

**Issue by saeedesmaili** [soberhacker/obsidian-telegram-sync#160]
Probably related to [this issue](https://github.com/soberhacker/obsidian-telegram-sync/issues/150).
I updated my plugin to 1.8 and started using the newly added `{{content:noFirstLine}}` variable in my template. Here is my template:

```
- [ ] {{creationDate:YYYY-DD-MM}}, {{creationTime:HH:mm}}

## {{content:firstLine}}
{{content:noFirstLine}}
{{file}}
```

When I send the following message on telegram:
```
Title
Some Text
```

This is what I get in Obsidian:
```
- [ ] 2023-15-07, 10:22

## undefinedTitle
undefinedSome text
```

**Comment by soberhacker** [comment]
Fix it in 1.8.1 release
