### ISSUE TITLE
"Error: EFATAL: Error: read ECONNRESET"

### ISSUE THREAD

**Issue by saeedesmaili** [soberhacker/obsidian-telegram-sync#178]
This is probably related to the [recently fixed issue](https://github.com/soberhacker/obsidian-telegram-sync/issues/149) on the bot connection. Since I have updated the plugin to 1.8.0 and 1.8.1, a bunch of error alerts appear on the right side of the obsidian (as captured in the following screenshot) and they don't disappear until I click on all of them one by one. Not sure what's causing this (it mostly happens when I leave the obsidian open and the laptop goes to the standby mode), but I wish they could at least automatically disappear after a few seconds.

<img width="330" alt="image" src="https://github.com/soberhacker/obsidian-telegram-sync/assets/13351748/1ebe8bc3-4b3f-419c-aa75-cdb7253499ec">

**Comment by soberhacker** [comment]
This has already been  implemented in the latest beta version. You can download it for testing in the Telegram channel -> https://t.me/obsidian_telegram_sync_insider/8

**Comment by soberhacker** [comment]
Done in official release 1.9.0
