### ISSUE TITLE
Subject: Feature Request: Options to Disable Debug Notifications and Auto-hide Notifications in Obsidian's Telegram Bot Connection Plugin

### ISSUE THREAD

**Issue by sfdrada** [soberhacker/obsidian-telegram-sync#179]
Dear Plugin Developer,

Amazing plugin, super useful for fleeting notes, I am writing to suggest a couple of features that could significantly improve user experience.

1. Disable Debug Notifications:

Currently, the plugin sends out debug notifications when connecting to the Telegram bot. While these are helpful for troubleshooting, they can be a bit intrusive when everything is functioning as expected. I would like to request an option to disable these debug notifications once the bot connection is confirmed to be working correctly. This could be a toggle switch in the settings menu of the plugin, allowing users to enable or disable the debug notifications as needed.

2. Auto-hide Notifications:

Additionally, I've noticed that notifications continue to hover on the screen until they're manually closed. This can be disruptive, particularly when users are focused on their work. I believe an auto-hide feature for these notifications would greatly improve user experience. This feature would allow notifications to disappear after a set amount of time, reducing screen clutter without requiring manual intervention. This could also be implemented as an adjustable setting, giving users the ability to control how long notifications stay visible before they auto-hide.

Both of these proposed features aim to give users greater control over their workspace and limit potential distractions, leading to a more streamlined and focused user experience. 

Thank you for considering these suggestions. I believe these improvements could make a substantial positive impact on the user experience of the plugin.

Great work,
Sage

**Comment by soberhacker** [comment]
Hi sfdrada! Thank you for using this plugin, and for your detailed description and justification for the feature request.

1. What debugging notifications are we talking about? Are you referring to the ones in the debug console?
2. This has already been partially implemented in the latest beta version. You can download it for testing in the Telegram channel -> https://t.me/obsidian_telegram_sync_insider/8
I've added more types of notifications to be automatically hidden. However, some errors should not be missed, so I don't see the need for a separate property for this. In the near future, I will add an icon to the status bar, which will allow even more notifications to be hidden.

Best regards,
soberhacker

**Comment by soberhacker** [comment]
No answer from customer

**Comment by sfdrada** [comment]
Mainly the notifications on the status of the telegram connection, this could be disabled or displayed as an icon to reduce screen clutter. Ideally these would be options in the plugin menu.

Thanks for your time,
Sage
