### ISSUE TITLE
RPCError: 400: TRANSCRIPTION_FAILED (caused by messages.TranscribeAudio)

### ISSUE THREAD

**Issue by adrianratajczak** [soberhacker/obsidian-telegram-sync#181]
Hi, I wanted to use the audio transcription feature but after transcribing the first few words the functionality stopped working altogether.
Can anything be done about it?
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/1114801/8b2e7687-8a5c-4baf-ae10-7526c5109983)

My template contains only {{voiceTranscript}} variable

**Comment by soberhacker** [comment]
Hi
Are you subscribed to Telegram premium?
