### ISSUE TITLE
The "Allowed chat from usernames (required)" setting ignores voice messages

### ISSUE THREAD

**Issue by Fertion** [soberhacker/obsidian-telegram-sync#183]
In the case of text messages, the bot refuses to process them if the login does not match the one specified in the settings, but it processes audio messages regardless of the settings

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/102726751/967df55a-e645-4b9c-9222-f5ae6b077a7b)

**Comment by soberhacker** [comment]
I have fixed this, try in the last prerelease [1.10.0.Beta](https://t.me/obsidian_telegram_sync_insider/12)
