### ISSUE TITLE
device not supported

### ISSUE THREAD

**Issue by frankcsliu** [soberhacker/obsidian-telegram-sync#193]
this app stopped working for my iphone 11 
![截圖 2023-08-18 10 08 53](https://github.com/soberhacker/obsidian-telegram-sync/assets/12545793/01106662-eeca-4dd7-aa7e-e9a8d2048e46)

i am not sure if i am the exeption or if i missed any important step of installation. but it seems that i cannot update this app due to the issue shown in the error message. thanks

**Comment by soberhacker** [comment]
Hi! This plugin is only for desktops and can't work on any tablets or smartphones. Also there isn't any possibility to add this support.
Please, use your PC or laptop for syncing.
