### ISSUE TITLE
First line of the note as a name of the file

### ISSUE THREAD

**Issue by meecosha** [soberhacker/obsidian-telegram-sync#197]
I wanted to make a template that would take the first line of the message and turn it into the note's name using {{content:[1]}} in the name of the template, but Obsidian doesn't allow ":" in the name. Are there any workarounds?

**Comment by soberhacker** [comment]
All unsupported symbols will be converted to "_".
But now it's not possible to customize the notes name. How did you want to do this?

**Comment by meecosha** [comment]
> All unsupported symbols will be converted to "_". But now it's not possible to customize the notes name. How did you want to do this?

I figured it out using the Templater

{{content:[2-]}}
<% tp.file.rename("{{content:[1]}}") %>

First it creates the body of the note starting from the second line, then renames the note using the first line of the message

_Btw, thank you very much for the plugin, it's amazing ❤️_

**Comment by soberhacker** [comment]
Soon I will implement templates for note and file names, so this problem will not be actual.

**Comment by soberhacker** [comment]
Hi @meecosha, you can now test the new beta release [2.0.0-beta.1](https://t.me/obsidian_telegram_sync_insider/16).

You have two ways to install it:
1. Manually, using the link above from our Telegram channel.
2. Directly from the plugin settings, via a special button. This button is only available if you're connected to Telegram as a user and are using a plugin version greater than 1.10.0.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/99afa579-888c-4e1d-ab3d-83e4407e3a44)

**Comment by soberhacker** [comment]
Release version 2.0.0 already published
