### ISSUE TITLE
How to add multiple telegram users?

### ISSUE THREAD

**Issue by peter-hanzo** [soberhacker/obsidian-telegram-sync#199]
Thanks for your plugin! Maybe this is a stupid question:
I try to add multiple users with separator: "," or ";" but it doesn't work

I couldn't find the answer in the documentation, although I'm sure the answer is not difficult.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/12713201/7f87992b-67a2-4c16-b26f-28eeb1bf429c)

**Comment by soberhacker** [comment]
Hi,
You were using an older version of the plugin. In those older versions, don't use spaces between usernames to avoid issues.

In the latest plugin version, spaces between usernames are no longer a problem, and you can also enter chat IDs in this field.
