### ISSUE TITLE
obsidian subfolder categorization via telegram hashtags (#nameofsubfolder in message)

### ISSUE THREAD

**Issue by otis5d** [soberhacker/obsidian-telegram-sync#200]
it would be great if i could quickly append a hashtag (#audio, #video, #readlater, #download) to messages and that would automagically put those messages in that hashtag's sub-folder

**Comment by soberhacker** [comment]
Hi
Test this feature in this beta release https://t.me/obsidian_telegram_sync_insider/21
Use {{content~#video}} to set condition for filtering messages

**Comment by soberhacker** [comment]
Release version 2.0.0
