### ISSUE TITLE
Append the content under a specific heading inside a specific note

### ISSUE THREAD

**Issue by Gourav1910** [soberhacker/obsidian-telegram-sync#210]
This issue is continue from telegram group.

It would be better if we can append the content under a specific heading without even break line (---) and just seperated by one blank line.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/101202140/54efbc94-efbf-41ed-af2a-985bad937d93)

And also if possible then there could be a option which will append the content in the form of list (dash or numbered). Well this is just for an extra option for potential use case.

**Comment by soberhacker** [comment]
Setting any delimiters is available in TS 2.1.0-beta.1 -> https://t.me/c/1913400014/26

**Comment by soberhacker** [comment]
Released in 2.1.0 production release
