### ISSUE TITLE
New Unfurl Variable Support

### ISSUE THREAD

**Issue by sepatel** [soberhacker/obsidian-telegram-sync#212]
Would be super helpful when posting a url link for example

```
https://lancedb.com/
```

as the entire content of the message, that we have the ability to reference the unfurl information such as the title of the url's title page, the quick blurb that is in the unfurl info, possible the image that went with it.

When you paste in telegram, slack, whatsapp, or a variety of locations, there is an unfurl action that takes place to essentially give you some contextual information. Nothing on the existing variables that I can find gives me anything more then the literal message contents which is the url stand alone.

I'd like a way to make a template that would allow me to structure the saved content to be more or less the unfurl information  similar to how you see it in telegram

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/190585/81b94f01-1112-449f-9c21-922d920cc6cb)

**Comment by sepatel** [comment]
Another better example

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/190585/3a39b269-047a-4251-9f52-affa74f798fb)

**Comment by sepatel** [comment]
Or perhaps an easier option would be to somehow allow other plugins to be triggered on the content for any url that is found? Something like https://github.com/dhamaniasad/obsidian-rich-links does the job but has to be triggered by hand. Maybe somehow a rule to allow external plugins to be triggered on any url found in the content?

**Comment by soberhacker** [comment]
Hi
Have you tried {{url1:previewYYY}}?

**Comment by sepatel** [comment]
> Hi Have you tried {{url1:previewYYY}}?

Yup, it's just a blank

**Comment by soberhacker** [comment]
Show me please an example (template + url)

пт, 29 сент. 2023 г., 20:22 Ryba ***@***.***>:

**Comment by sepatel** [comment]
> Show me please an example (template + url) пт, 29 сент. 2023 г., 20:22 Ryba ***@***.***>:

For example:
Template:
```
{{url1:preview250}}
```

Note:
```
<iframe width="100%" height="250" src="https://www.virtualizationhowto.com/2023/09/signoz-free-and-open-source-syslog-server-with-opentelemetry/"></iframe>
```


Actual expectation should be closer to
```
<div class="rich-link-card-container"><a class="rich-link-card" href="https://www.virtualizationhowto.com/2023/09/signoz-free-and-open-source-syslog-server-with-opentelemetry/" target="_blank">
	<div class="rich-link-image-container">
		<div class="rich-link-image" style="background-image: url('https://www.virtualizationhowto.com/wp-content/uploads/2023/09/SigNoz-Free-and-Open-Source-Syslog-server-with-OpenTelemetry.png')">
	</div>
	</div>
	<div class="rich-link-card-text">
		<h1 class="rich-link-card-title">SigNoz: Free and Open Source Syslog server with OpenTelemetry</h1>
		<p class="rich-link-card-description">
		SigNoz is a free and open-source syslog server and open telemetry solution allowing viewing metrics, query log data, dashboards, and alerting
		</p>
		<p class="rich-link-href">
		https://www.virtualizationhowto.com/2023/09/signoz-free-and-open-source-syslog-server-with-opentelemetry/
		</p>
	</div>
</a></div>
```

**Comment by soberhacker** [comment]
Unfortunately, this variable is all I can offer you. It would be more appropriate to create an issue for the plugin responsible for generating the 'rich links' you sent me. It would be easier and more correct for them to handle it from their end.

**Comment by sepatel** [comment]
> Or perhaps an easier option would be to somehow allow other plugins to be triggered on the content for any url that is found?

This was the ask I had of you, I need a way in your plugin since it is the *only* thing that actually processes the message that comes in for me to be able and trigger another plugin for any of the url's found in it. There are already a lot of plugins which can do the job but there is not a way to actually trigger them because there is no callback or hook or anything to do so. I was hoping for something like a 
```
{{url1:plugin-nameOfPlugin}}
```
where I can have it actually use correct things as it is the telegram sync plugin that is prohibiting me from being able to identify and use other plugins to start with. I should be able to sync the content that is posted to telegram to obisidan with this sync plugin but currently it is leaving out the unfurl and not providing a way for me to work around that as well.

**Comment by soberhacker** [comment]
Thank you for elaborating on your request. I fully comprehend the functionality you are seeking. Unfortunately, I am unable to fulfill this specific request at this time. Should Telegram API offer the unfurl data, I would be more than willing to integrate this feature. Regrettably, leveraging external services is not an option I can explore. I recommend that you create an issue for the plugin that already implements rich links. Obsidian allows any plugin to track the creation of note files and perform operations on these files.
