### ISSUE TITLE
Looses connection and doesn't reconnect

### ISSUE THREAD

**Issue by Di3mex** [soberhacker/obsidian-telegram-sync#213]
I am running Obsidian on my Macbook and I basically never close Obsidian. I have noticed that after some time Telegram Sync looses connection and is unable to regain it. I can fix it by either restarting Obsidian or disabling/enabling Telegram Sync.

``` txt
WebSocket connection to 'wss://venus.web.telegram.org/apiws' failed: 
W3CWebSocket @ plugin:telegram-sync:16439
```

**Comment by soberhacker** [comment]
1. What do you mean by "loses connection"? The user connection, the bot connection, or both?
2. Have you tried sending a message to your bot? What happens?
3. How long did you wait for the connection to be restored? Usually, it tries to reconnect every 2 minutes.

**Comment by Di3mex** [comment]
1. The Obsidian plugin doesn't load the messages. The bot doesn't "acknowledge" the messages I sent
2. The bot doesn't acknowledge the messages
3. Hours, it doesn't reconnect

This is what I see in the console right now. I sent messages this morning at 8am, now its 11:30 and the Telegram.chat file for this day hasn't been created yet.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/966375/9b0fb76a-aded-4b45-881e-41de68eb766d)

After reloading the plugin:
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/966375/3d05f838-ff47-4cd9-9ffd-964058e8f53f)

I am running version 2.0.0. I will hold back on updating until you respond.

**Comment by soberhacker** [comment]
The last production version of plugin is 2.2.0. Why are you holding back  2.0.0?

**Comment by soberhacker** [comment]
I can't reproduce this bug :( As I understand it, you have connected both your bot and your Telegram user, correct? Could this bug occur more frequently after waking your laptop from sleep, or after opening many applications simultaneously? Or maybe you mentioned other triggers?

**Comment by soberhacker** [comment]
Ironically, right after writing I couldn't replicate the bug, it occurred. I'm going to investigate this further 🫣

**Comment by soberhacker** [comment]
Test this version please [telegram-sync_3.0.0-beta.4.zip](https://github.com/soberhacker/obsidian-telegram-sync/files/13451533/telegram-sync_3.0.0-beta.4.zip)

To install copy main.js to PAST-HERE-YOUR-VAULT-PATH/.obsidian/plugins/telegram-sync/ and restart Obsidian (or the plugin)
