### ISSUE TITLE
Forward slash from URL in the message triggers nested paths

### ISSUE THREAD

**Issue by SaQDS** [soberhacker/obsidian-telegram-sync#215]
This is my note path template: MyNote/{{content:30}}.md 
If I send https://www.youtube.com/watch then message will be created in the nested format, shown as attachment. 

![obsidian-telegram](https://github.com/soberhacker/obsidian-telegram-sync/assets/28286890/d7674134-ab77-4e8d-b56f-eb2271ef244a)

**Comment by soberhacker** [comment]
Fixed in TS 2.1.0-beta.1 -> https://t.me/c/1913400014/26

**Comment by soberhacker** [comment]
Fixed in 2.1.0 production release
