### ISSUE TITLE
Does not sync previous days content

### ISSUE THREAD

**Issue by sepatel** [soberhacker/obsidian-telegram-sync#216]
Perhaps I'm misunderstanding how this works but I did not have obsidian running over the weekend (was traveling) so thus the sync was not running. I continued however to leave notes to myself and put links to the sync channel in telegram. So I had combination of notes and links on 9/30, 10/1, and today 10/2. I also have it setup to remove the posts when it syncs down as well.

When I turned on obsidian today, the sync only removed the posts make today, not the previous 2 days. When I looked in obsidian sure enough it did not make a folder for 9/30 or 10/1 and write any of the notes down for those 2 days. It only created a folder for 10/2 and put all of the messages sent today into the folder.

I'm pretty sure this is a bug but if it is not, can it be enhanced to check for any new messages since the last time it sync'd perhaps? Or something, it would be really helpful to not have to guess as to which messages did and did not get sync'd up (which is why I have it deleting messages that are sync'd up but I'm guessing most people do not do that).

More importantly, I'd really like to be able to get the notes into obsidian without having to manually rewrite everything into obsidian by hand (kinda defeats the purpose of the sync plugin).

**Comment by sepatel** [comment]
> telegram server does not store messages for bots longer than 24 hours

oh shoot :-( , there aren't any configurations or flags that I can set to mitigate this I presume, is there a roadmap on telegrams end to expand this. Is there a way to query for messages that do exist on the server explicitly perhaps. A way for me to point the bot to reprocess or something?

**Comment by soberhacker** [comment]
@hmnijp thanks for helping to answer
@sepatel It will be possible by connecting your telegram user to the plugin, not by bot. I am planning to implement such a feature next month

**Comment by soberhacker** [comment]
The beta release of this feature is here https://t.me/c/1913400014/36
The official production release will not be earlier than in 1 month.
So, I recommend starting to test and use it right now

**Comment by sepatel** [comment]
Sorry but I only saw this message today, love to test it but am unclear on the full instructions maybe. Essentially I just turn off obsidian, renamed the old main.js file and drop this new one in its place? None of the other files change (so it still says version 2.2.0) and the sync is still running but I don't have to reconnect or reconfigure anything. Presumably any new messages moving forward will get picked up now if obsidian is not running for over 24 hours from the time of the message but old messages sitting there will still not get picked up right?

I'll be putting it to the test starting today but want to make sure that I understand everything correctly.

**Comment by soberhacker** [comment]
Yes, you need to:
- Connect your user account.
- Subscribe to the Telegram Sync Insider channel.
- Add chats in the plugin's settings that will be monitored for messages older than 24 hours during the plugin's launch.
