### ISSUE TITLE
Update Broke my syncing?

### ISSUE THREAD

**Issue by flowingblaze** [soberhacker/obsidian-telegram-sync#220]
Hello, I use obsidian on windows 10 and I use telegram on android. I had the settings set up so they all go into one note. When I updated the plugin, this is no longer the case and I cannot find the setting to change it. I'm aware this isn't exactly a bug report so sorry if this is the wrong place to ask for help on this, but how do I make it so all the messages to the bot I set up go into one note?

**Comment by soberhacker** [comment]
Hello
Send me a screenshot of the main page of the plugin settings 
Now you can set note path template and set any name for your note
https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/eeeaf37f-0252-47f2-9153-473710e2b414)
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/21ab44e8-6d93-4f06-b059-106f994d1fd2)

**Comment by flowingblaze** [comment]
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/107226733/48e7d008-62d2-4191-84e2-b751ce665c9d)
