### ISSUE TITLE
Always connecting, never connected

### ISSUE THREAD

**Issue by yenan3** [soberhacker/obsidian-telegram-sync#225]
Hi soberhacker,

I entered Bot token and my username in Bot(requied) in Obsidian V1.4.16 and Telegram Sync 2.2.0 plugin settings page. But it is always shows connecting... It never connected, not even once.

Firstly, I thought the root cause is the parameters of bot token or username is invalid. So I tried the same parameters in logseq plugin named Indox Telegram v0.1.4. And the parameters worked fine.

Secondly, I thought it's casued by network blocks in China. I changed VPNs but the plugin is still not working. I also tried logseq Inbox Telegram plugin in the same PC via same VPN I used for Obsidian Telegram Sync, it works well. I believed the network is not the root cause.

**Comment by yenan3** [comment]
Hi soberhacker,

Thanks for the quick reply.

1. I'm not familar with how to find errors in developer console. I tried and the console said 20 errors and 2 issues, you can see in the following screenshot. 
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/bf719f7c-2aaf-4bdd-a3b7-11f21a93b9ff)
2. The browser shows the following screenshot after I visit the link you provided.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/07a9b03c-a7bc-45a7-98d5-59f18dbfa190)
3.1. Tried to connect my telegram bot, but it's always connecting
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/ae13320b-a05c-4b3d-8911-0f538ce9fab7)
3.2. The logseq plugin works fine. See the following screenshot for plugin setting page.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/4deec2e5-6ebf-47c4-a936-34dcb4d4cd24)
3.3. You may find more detials in following screenshots.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/2b9182ea-ec10-4aaf-bbb7-74ab95c386dc)
3.4. The logseq plugin work well with telegram, but in the same PC the obsidian plugin doesn't
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/652d1679-63b3-47c2-aa4d-ef093b118fa4)

**Comment by soberhacker** [comment]
Thanks for your report.

1. The 'Issues' tab is not what I was expecting. Please refer to the Console tab.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/ee3baf3c-7fda-4d7b-beae-929d6cf0b513)

2. I'm 90% sure that the issue lies either with your system settings (such as antivirus software or firewall) or with the compatibility between your VPN and Obsidian. Try to seek help in the China Telegram group: https://t.me/obsidiangroup

**Comment by yenan3** [comment]
1. Please see the errors in Console tab
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/c042557b-7be0-4835-92a6-05e8ec1d3819)

2. I update the result of visiting the link.
![image](https://user-images.githubusercontent.com/60581695/277956765-c6ca64e6-6f41-459d-80b1-e4c9328edd60.png)

**Comment by yenan3** [comment]
I found more errors in Console tab, you can see the following screenshots:
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/ba60ba44-10dc-4b43-a5c2-4ac3887e0f64)

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/0b481dde-cb78-4a40-bfa6-9349bb4c3ecf)

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/767fe4c4-835a-4481-8aff-74571230c4b0)

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/28441486-5014-4d5c-b76b-f09657f2e34e)

**Comment by yenan3** [comment]
Here are more details of error about Telegram Sync.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/9037d410-0f2a-4c53-ac52-6c77bc804912)

**Comment by yenan3** [comment]
Hi Soberhacker.

I have TUN mode turned on in Clash and it can be CONNECTED!

**Comment by soberhacker** [comment]
Great job! Now if anyone asks, I'll definitely point them your way for guidance.
Thanks

**Comment by yenan3** [comment]
If this issue will come in handy for others, let me expand on how to turn on TUN mode. I'm using Clash for Windows, and using version 0.20.19 as an example

1. General --> Service Mode --> Manage --> Install 
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/60581695/770eb7eb-4a40-4dab-99d2-56eeac0fff40)

3. Turn on TUN mode and Mixin 
3. Turn off System Proxy

**Comment by soberhacker** [comment]
Brilliant! I've already started adding this explanation to the plugin.
