### ISSUE TITLE
Transcript Voicenotes Telegram Premium

### ISSUE THREAD

**Issue by santiyounger** [soberhacker/obsidian-telegram-sync#227]
Hey thanks for the amazing plugin!

Can you please help me with instructions on how to get voicenote transcripts on Obsidian.

I just paid for Telegram Premium to achieve this, but I don't know how to set it up so that the transcript is sent to Obisidian with this plugin.

Thanks

**Comment by soberhacker** [comment]
Hi, Thank you for using the plugin!
Here is a short manual:
1. Connect your Telegram user in the plugin settings
2. Edit distribution rule -> add template file and add into file variable {{voiceTranscript}}

**Comment by santiyounger** [comment]
great thank you, I mentioned your plugin in my latest [YouTube video](https://youtu.be/YstDFpvFeow?si=VWxBoEUNNm_XmiZ_) and added some tutorial to my free community.

Loving it, thank you for your great work!
