### ISSUE TITLE
Being able to append under selected heading

### ISSUE THREAD

**Issue by connradolisboa** [soberhacker/obsidian-telegram-sync#228]
Like the quick add feature, selecting a line/heading to append the notes.

**Comment by soberhacker** [comment]
Not clear, please add details

All the features, that I am considering in my head are already implemented :)

**Comment by connradolisboa** [comment]
So my daily notes have several Headers (Entries, Log, Journal)  if in my telegram sync filter is set to /path/Calendar/YYYY-MM-DD the text will be appended to the end of the note.
It would be nice if we could append to any heading we like. Just like with quickAdd "Insert Under".

**Comment by soberhacker** [comment]
You can set 3 distribution rule:

path/Calendar/YYYY-MM-DD-Entries
path/Calendar/YYYY-MM-DD-Log
path/Calendar/YYYY-MM-DD-Journal

or

path/Calendar/YYYY-MM-DD/Entries
path/Calendar/YYYY-MM-DD/Log
path/Calendar/YYYY-MM-DD/Journal

**Comment by connradolisboa** [comment]
That creates another note YYYY-MM-DD-Entries
Let's say this is my note
2023-08-11
## Entries

## Journal

## Log

Through telegram sync filter options it could have a way to choose if to append under ## Entries, Journal or ## Log

**Comment by soberhacker** [comment]
Yes, I got it. What are advantages to keep one note instead of creating
three separate? Give me motivation to implement this feature )))

**Comment by connradolisboa** [comment]
XD. Organization and quick access to what you've added to your vault in a specific day. Multiple headings/sections in daily notes is quite common.
This feature would allow for other use cases too. For adding cards in kanban boards (each list is a heading) for example. Or even I've seen users that keep ## Developments above their notes on projects, this way they can append notes above the fold without messing with the yaml fields (when you select to add messages to the top). There are ways to extroplate this feature too. Like allowing {{content[1]}} to be used in "Insert after line" field. That way someone can choose where in their files they want to append the note, in a projects note when you want to add under the 
 Resources heading. My project notes for example have headings like Tasks, Resources, Mind Dump.

**Comment by moiSentineL** [comment]
bump

**Comment by soberhacker** [comment]
Implemented starting from v. 3.1.0
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/77a120b6-6076-4583-8071-6699ff7af14c)

**Comment by delorum** [comment]
Hello! Many thanks for a very good plugin!
Addition to that feature about heading: when someone specify a heading, new messages appear under that heading but in reverse order. Newer messages apear directly under a heading, not at the end of the section. Is there a way to change that? "Reverse Order" setting does something different
