### ISSUE TITLE
The notes don't appear, when there's only one row in the message because of the specific template

### ISSUE THREAD

**Issue by meecosha** [soberhacker/obsidian-telegram-sync#229]
I have the body of the note set as `{{content:[2-]}}` and the Note path template as `+/{{content:[1]}}.md`. The idea was to make empty files with a name, if the message contains only one row. But the files simply don't appear, when the body template isn't satisfied and there's no second row.

But they appear, when there are two rows, first one becomes the name, and the second — the body.

**Comment by soberhacker** [comment]
I am not plaining to implement creating empty notes.
But, you can add to your template ZERO WIDTH SPACE
You can copy this symbol here https://unicode-explorer.com/c/200B
