### ISSUE TITLE
Problems with adding images to note creation

### ISSUE THREAD

**Issue by Detluff** [soberhacker/obsidian-telegram-sync#230]
I usually redirect notes with attached pictures from favorites to bot, but they end up not attaching. The same thing happens if you copy the text and paste it in the bot, and then copy and paste the picture in the bot.

It says: ...❌....
Error: File names cannot end with a dot or a space.

I don't understand what it means in my case. Perhaps the problem is due to my editing settings in the plugin.
![1](https://github.com/soberhacker/obsidian-telegram-sync/assets/146100378/42634176-bbad-459b-98b1-1a45bf3c6329)

**Comment by soberhacker** [comment]
It is a bug. The error message isn't relevant in this case. If you add the folder at the beginning, then it will work as expected, but at the moment, you can't store in the root of the vault.

**Comment by Detluff** [comment]
Yeah, it worked. Thank you
