### ISSUE TITLE
When using line break before text, indetation is used instead

### ISSUE THREAD

**Issue by connradolisboa** [soberhacker/obsidian-telegram-sync#231]
What happens:
My template:

- {{content:text}} 
(end of template)

My message:
Test note 123

When appended to the daily note (consider the space between the notes the same as a tab space, I know it because it deletes the whole space if I press backspace once

- Note Before this               - Test note 123

**Comment by connradolisboa** [comment]
Github didn't show the space between "this" and "- Test note 123"

**Comment by soberhacker** [comment]
Hi
Could you please send screenshots of what you need and what you have, because from this text description it is not clear

Thank you

**Comment by connradolisboa** [comment]
Hey! I thought it was a bug but after adjusting the template I managed to do what I wanted!
