### ISSUE TITLE
New messages only send the 1st message sent

### ISSUE THREAD

**Issue by nateopr** [soberhacker/obsidian-telegram-sync#232]
Hello,

I have everything set up I think, but when I send a message in telegram, it appends the note with whatever the 1st message I sent was, instead of the new message. 

For example:

In telegram, it looks like this. Each line is a new message:
- 1
- 2
- 3
- 4

On the appended note, it looks like this:
Forwarded from user
- 1
Forwarded from user
- 1
Forwarded from user
- 1
Forwarded from user
- 1

The following are screenshots of the settings I have for the plugin.

Any help would be appreciated! Thanks!

<img width="723" alt="Screenshot 2023-11-16 at 2 36 01 PM" src="https://github.com/soberhacker/obsidian-telegram-sync/assets/12939162/525a9edb-6623-47eb-9ed4-e27b2528d3ae">
<img width="554" alt="Screenshot 2023-11-16 at 2 36 11 PM" src="https://github.com/soberhacker/obsidian-telegram-sync/assets/12939162/cc06b719-f811-47a5-9706-8276caeb2861">

**Comment by soberhacker** [comment]
You have the same Template file and Note path. There are different concepts
