### ISSUE TITLE
Some messages not coming through to Obsidian, even if bot confirms they did

### ISSUE THREAD

**Issue by santiyounger** [soberhacker/obsidian-telegram-sync#233]
Hey, incredible plugin, thank you for your excellent work!

 I mentioned this plugin at the end of my [YouTube video](https://youtu.be/YstDFpvFeow?si=DwmF_hnHniK-GOEg) and even created some free tutorials for it on my free community.

It's been very reliable, but the last couple of days some messages from telegram aren't coming through to Obsidian, it feels random, since if I send 5 messages, maybe 2 and 5 come through, but 1,3,4 don't.

It seems random since some messages do come through to my .md on Obsidian, but some just don't. And the telegram bot likes all of them in the chat, even the ones that don't come through:

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/51902730/74b7db9c-1507-498b-b9de-2e409dd411fe)

I send a bunch of messages through my phone, sometimes several in the same minute, and through the whole day.

Then in the mornings or evenings I open my obsidian on desktop for them to sync. Sometimes I do it next morning or longer, not sure if there's a 24 hour limit or something though.

Here are my settings

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/51902730/51b381d1-d328-41c4-a362-6051712bfe85)

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/51902730/5828cf28-2384-4ab6-9d9e-529b05fd6d4f)

## template file
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/51902730/6c459c78-263e-4d67-b84b-14d43c304c1e)

## this is what the message comes through as in Obsidian
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/51902730/427e3282-6b25-451f-aeec-5841247f7d72)

thank you!

**Comment by soberhacker** [comment]
Hi! Thank you for your manuals and even promotion!

Please, check the developer console (Ctrl+Shift+I) when you get this problem again. 

 
P.s. If a message is liked, then it is not older than 24 hours for sure.

**Comment by santiyounger** [comment]
My pleasure, hope more people discover your work with this great plugin, I'll make sure to keep recommending it.

Sounds good I'll keep an eye. 

For the developer console (Ctrl+Shift+I) you mean inside of Obsidian? if so what should I look out for?

Thanks

**Comment by soberhacker** [comment]
Yes, inside Obsidian. Press Ctrl + Shift + I to open the developer panel. You should look out for errors in the console. But anyway, send me the log from the console if some messages are skipped.
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/2ffa618d-7081-44ba-8cdb-ad8fea505c63)

**Comment by santiyounger** [comment]
alright thank you if I spot errors like this again I'll let you know thanks
