### ISSUE TITLE
Obsidian Mobile

### ISSUE THREAD

**Issue by bitSheriff** [soberhacker/obsidian-telegram-sync#236]
Currently it is not possible to enable the plugin on Obsidian Mobile.

It would be great to be able to sync the messages on Mobile too, to avoid merging issues (syncing) if the messages are embedded into a file which is frequently edited.

Thanks, great job with this plugin 😃,  love the possibility to quickly note things down (Obsidian Mobile takes an eternity to open)

**Comment by msnr** [comment]
Its stated literally on top of readme:
"This plugin is only available for desktops and would never be available on mobile platforms."
😅

**Comment by bitSheriff** [comment]
thank you for the quick answer :see_no_evil:
