### ISSUE TITLE
Add proxy setting support

### ISSUE THREAD

**Issue by alerezaaa** [soberhacker/obsidian-telegram-sync#237]
Hi there

Amazing plugin I found today

As you know Telegram is blocked in some countries like Iran, and due to that, Telegram added proxy support itself.

Please add proxy setting support which helps in this countries ( commonly **socks5** or **http** )

Thanks

**Comment by soberhacker** [comment]
Hi! Unfortunatelly I am not going to create such feature. You should request proxy settings in general for Obsidian. Or use VPN or system proxy (Clash for windows etc)
