### ISSUE TITLE
not connecting

### ISSUE THREAD

**Issue by AlexRaycan** [soberhacker/obsidian-telegram-sync#238]
![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/103534203/b5eada1e-05a5-48a2-8d86-ba8f719bd8e0)

all time shows this. and nothing happened. close-open obsidian doesn't help. the latest version

**Comment by soberhacker** [comment]
Hello
Is it actually?

**Comment by AlexRaycan** [comment]
Hello. Today it's worked. Thank you
