### ISSUE TITLE
You can't edit massages

### ISSUE THREAD

**Issue by kudrmax** [soberhacker/obsidian-telegram-sync#239]
1. Close Obsidian
2. Send message to telegram bot
3. **Edit** message
4. Open Obsidian

The message that was before editing will be sent

**Comment by soberhacker** [comment]
Fixed. You can download the beta version here: [Insider Channel](https://t.me/c/1913400014/47).
Or, wait 1-2 weeks for the production release.

**Comment by soberhacker** [comment]
Fixed in 3.1.0
