### ISSUE TITLE
Does the {{replace}} template variable support regex (apart from \n)?

### ISSUE THREAD

**Issue by aulline13** [soberhacker/obsidian-telegram-sync#268]
Same as in the title

**Comment by a13ph** [comment]
Judging from code, it seems like it supports regex, but I haven't tried
https://github.com/soberhacker/obsidian-telegram-sync/blob/bbdddc2bf3128931ed1a570092cbd69f417b00b1/src/telegram/bot/message/processors.ts#L137

**Comment by soberhacker** [comment]
Hello

No, it doesn't
