### ISSUE TITLE
Update or Remove separator when append to file

### ISSUE THREAD

**Issue by soundlicious** [soberhacker/obsidian-telegram-sync#269]
It would be nice to be able to update the separator or even being able to remove it.
Whenever Telegram sync append to my file, there is constantly the separator "***\n" that I need to remove every time.

**Comment by soberhacker** [comment]
Hello
It is already possible

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/ccf39205-5407-49d0-9224-10ac9d30cead)

**Comment by soundlicious** [comment]
My bad, my version wasn't up-to-date 😵‍💫
