### ISSUE TITLE
Cant pay for Insider program

### ISSUE THREAD

**Issue by andromedarabbit** [soberhacker/obsidian-telegram-sync#271]
<img width="479" alt="image" src="https://github.com/soberhacker/obsidian-telegram-sync/assets/2077947/79d9c02b-fa59-43d7-addf-080ad08ea71e">

<img width="272" alt="image" src="https://github.com/soberhacker/obsidian-telegram-sync/assets/2077947/d412ffa6-3cad-43e2-8575-b15b3bb54220">

**Comment by soberhacker** [comment]
Thank you for pointing out the issue. The @donate bot lost the competition to the @tribute bot for accepting donations and organizing subscriptions, so it has suspended the acceptance of payments. On the bright side, all settings can be automatically transferred to the @tribute bot. You can now subscribe to the insider channel using this link:

[](https://t.me/tribute/app?startapp=s1uX)
