### ISSUE TITLE
Ho to ignore formfating (bold, italic, underlined text) in the notes names?

### ISSUE THREAD

**Issue by NikMAX2077** [soberhacker/obsidian-telegram-sync#272]
Problem:
In my config I'm using the first message line to name my note. But if that first line contains special formatting (like bold, italic, underlined text, etc.) I get a special symbols in my note's name. For example, if my message starts with bold line "**Note name**", I have `__Note name__` instead of `Note name`.
Unfortunately, I didn't find any examples in the docs that would solve this problem. Is it possible to fix it right now? If not, it would be very helpful to add this feature in the future releases.

**Comment by soberhacker** [comment]
Try new 3.2.0 release!
