### ISSUE TITLE
Simplify one file telegram log

### ISSUE THREAD

**Issue by dxcore35** [soberhacker/obsidian-telegram-sync#273]
Is it possible to create ONE FILE with this format?

```
# 2024-05-12
- 08:00: Testing message
- 19:30: Another message
```

I dont want to see the text "forwarded from", I will be only one using this. I see this unnecessary.
Thank you very much. Amazing plugin, this was really missing feature for quick add via mobile phone.

**Comment by soberhacker** [comment]
Thanks :)

Yes, it is possible

create following template file and use it in your distribution rule

{{messageTime:HH:mm}}: {{content:text}}


More details you can find here

https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs%2FTemplate%20Variables%20List.md

**Comment by dxcore35** [comment]
Thank you very much for quick reply! The template works.

What I would like add is that command
`{{content}} - forwarded from + file | image + message text`

I would like to have command that with produce
`{{content:clean}} - file | image + message text`

Basically it will remove "forwarded from" or you can read allowed user from plugin settings and then you will omit "forwarded from".

Again thank you for the plugin. It is going to change the way I'm using the Obsidian. Looking for more integration with daily notes! 🎶

**Comment by soberhacker** [comment]
![Screenshot_20240211-214408.png](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/a9dac86d-b95b-4f0b-9585-0300fd99b9ea)

It is also possible

**Comment by soberhacker** [comment]
Combine variables as desired :)

For assistance, feel free to inquire within the Telegram community
[Telegram Chat Group](https://t.me/ObsidianTelegramSync)
