### ISSUE TITLE
Expand parsing into daily note [feature request]

### ISSUE THREAD

**Issue by dxcore35** [soberhacker/obsidian-telegram-sync#275]
It will be amazing to add text into daily note. After some header for example after header # Log.
In this way the Bot will become quick add for daily note, journal. It is only as idea.... Maybe somebody can elaborate more here...

Thanks!

**Comment by soberhacker** [comment]
I'm completely lost

I think it is already implemented
https://github.com/soberhacker/obsidian-telegram-sync/issues/228

**Comment by soberhacker** [comment]
3.1.0 

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/db124aa9-0ed6-4ef0-9aca-ee0e7974b2ce)

**Comment by dxcore35** [comment]
The problem is daily note doesn't need to be created that time... and daily note is using its own template

**Comment by soberhacker** [comment]
You have to describe more and with real examples. Because I don't understand the problem
