### ISSUE TITLE
FR: Make Insider feature "Process old messages" available not only on plugin reload

### ISSUE THREAD

**Issue by mnaoumov** [soberhacker/obsidian-telegram-sync#286]
Currently Insider feature "Process old messages" works only on plugin reload. But it would be useful if this check is executed on some other events as well, such as running on schedule and having it is as a custom invocable command

**Comment by soberhacker** [comment]
It is not clear why you need to process old messages when the plugin is not just reloading. If the plugin operates continuously, there won't be any old messages. Conversely, if the plugin doesn't work, scheduling and command become unnecessary.

**Comment by mnaoumov** [comment]
@soberhacker in my case, Obsidian is open all the time but it's not doing anything with the computer goes into the sleep mode. When the computer wakes up from it, it doesn't process the old messages appeared during the sleep time

**Comment by soberhacker** [comment]
Ok, I will add processing of old messages after waking the computer from sleep

**Comment by mnaoumov** [comment]
Sleep mode is not the only trigger. For example what if the router was disconnected for some time and you didn't have Internet...

**Comment by mnaoumov** [comment]
I guess more realistic trigger would be to compare with the last successful fetch attempt and if it was way too far away, trigger the reload

**Comment by soberhacker** [comment]
Try new 3.2.0 release!

P.S. I thought it would be easy, but in reality, it was fucking hard :)
