### ISSUE TITLE
How do I put all the telegram messages in one file?

### ISSUE THREAD

**Issue by flowingblaze** [soberhacker/obsidian-telegram-sync#291]
Hello, I tried to get help with this a few months ago on #220 but It was closed and when I sent the settings after It was closed no one saw it. I decided to go back to telegram sync but I sitll need all the telegram messages in one file and that is not working still.

**Comment by Thersamauruk** [comment]
Hi, do specify such a line in the settings below. And you will receive all messages in the Telegram folder in separate files created by the date of the messages

Telegram/{{messageTime:YYYYMMDDH}}.md

![изображение](https://github.com/soberhacker/obsidian-telegram-sync/assets/170223688/7fba55bb-4a7b-474c-92b3-2fbceb838b57)
![изображение](https://github.com/soberhacker/obsidian-telegram-sync/assets/170223688/c25f6487-ef52-44d3-9ff1-9fa93358ffa7)

**Comment by soberhacker** [comment]
@Thersamauruk Thanks!
