### ISSUE TITLE
The link to the forwarded message doesn't work

### ISSUE THREAD

**Issue by Thersamauruk** [soberhacker/obsidian-telegram-sync#292]
Hi, thanks for the great plugin. But the link to the forwarded message does not work for me, I use these variables
{{chat}}
or
{{forwardFrom}}
In the Obsidian note, I get a link to a message from a chat with a bot

I checked the same messages by forwarding them to my Telegram favorites. There is an opportunity to return to the original message.

**Comment by soberhacker** [comment]
Hi Thersamauruk!
I need an example of such message. Because I can't reproduce the bug. It's running perfectly on my end :)
send here https://t.me/soberhacker
