### ISSUE TITLE
If some messages are sent at the same time - combine them into one event/note.

### ISSUE THREAD

**Issue by hmnijp** [soberhacker/obsidian-telegram-sync#293]
I suggest a function:
1) the ability to combine at the same time forwarded messages into one event/group/note (arriving in a short time interval)
2) mark the first message of the group as {{comment}} content variable. (check may be needed: `if {{user:name}} = "myname" & not(forwaredFrom..)...` etc.)

![Drawing 2024-05-22 14 10 00 excalidraw](https://github.com/soberhacker/obsidian-telegram-sync/assets/51473247/d7bf9685-e853-436b-aba4-f697eeb2e4e3)

For example the first case:
   by forwarding a message or a long dialogue to the bot and adding a comment - the bot receives several messages and creates a note for each, which is not convenient.. The first of which is my comment (mark it for using templates - quote, etc.), the rest of the forwarded messages as {content}.

Second case:
   a lot of pictures are sent to the bot, the telegram unites them in groups of no more than 10 - they are also imported as different notes. In this case, there is no comment - this requires a check - "whether the first message is a comment or not." Then you can simply combine them into one note.

**Comment by soberhacker** [comment]
It is difficult to implement. You need both a beginning and an ending signal. Any solution I can think of is not ideal. Try to handle this issue with Distribution Rules and the File Path Template. For example, you can create a separate channel, group, or topic, add the bot there, and send such messages only to this group. In the path template, use only elements that are common to all of these messages, such as the time {{messageTime:YYYYMMDDHHmm}}.
