### ISSUE TITLE
Select my own messages and forwarded from somewhere

### ISSUE THREAD

**Issue by Outsider-corp** [soberhacker/obsidian-telegram-sync#296]
Hi, I'm really interested in your plugin, it's amazing)

One moment: I want to create 2 rules: 1st rule will send my own messages to note1.md, and 2nd rule will send all forwarded messages to note2.md

How can I do it?

**Comment by soberhacker** [comment]
**Option 1:**
1. First rule - set filter by user.
2. Second rule - set filter to `{{all}}`.

**Option 2:**
1. Create a group with topics.
2. Send your messages in the first topic, and forwarded messages in the second topic.
3. Set filters by topic.

More information can be found in the [manual](https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md).
