### ISSUE TITLE
How to disable automatic emoji Insertion for sync messages?

### ISSUE THREAD

**Issue by plagness** [soberhacker/obsidian-telegram-sync#312]
Hello!

I want to use it in the chat, but the automatic emojis annoy people a lot. Additionally, Telegram often glitches with such a large number of emojis, making it impossible to remove the reaction icon.

**Comment by soberhacker** [comment]
Hello!
Currently, this feature is not available, and you are the first to request it.

In the plugin's channel, [Obsidian Telegram Sync Insider](https://t.me/obsidian_telegram_sync), I conduct polls to determine which features should be prioritized for development. However, before a feature can be added to the channel poll, it needs to be requested by at least a few users here on GitHub issues. Alternatively, you can promote your feature in the chat [Obsidian Telegram Sync](https://t.me/tribute/app?startapp=sfFf)

Thank you for your understanding

**Comment by soberhacker** [comment]
@plagness 

Try this version:
https://t.me/obsidian_telegram_sync/65

**Comment by vascowhite** [comment]
I also find the automatic emojis annoying. I have just installed version 4.0.0 , how do I switch them off. I don't see anything in the settings.

Awesome plugin by the way!
