### ISSUE TITLE
Filtering Messages by Channels

### ISSUE THREAD

**Issue by Crusader-83** [soberhacker/obsidian-telegram-sync#313]
I wanted to filter all messages which are forwarded by a certain channel with the function {{forwardFrom=Value}}
This didn't work out
Then I added {{all}}{{forwardFrom=Value}} that didn't work aswell
Help

**Comment by soberhacker** [comment]
The channel name must be complete and absolutely accurate, including emojis and Unicode characters. For example, {{forwardFrom=𝔸𝔽 𝕍𝔸𝕌𝕃𝕋 🇺🇸}}

{{all}}{{forwardFrom=Value}}: such a condition doesn't make sense. It should be divided into two distribution rules. For example, the first rule has the condition {{forwardFrom=𝔸𝔽 𝕍𝔸𝕌𝕃𝕋 🇺🇸}} and creates notes only for the 𝔸𝔽 𝕍𝔸𝕌𝕃𝕋 channel in a folder named 'Favorite channel'. The second rule has the condition {{all}} and creates notes for all other messages in the 'Others' folder
