### ISSUE TITLE
Saving stickers

### ISSUE THREAD

**Issue by sempaitakoo** [soberhacker/obsidian-telegram-sync#317]
Now it is possible to save the text of the message, video, image, etc. However, **telegram stickers are ignored**.

![image](https://github.com/user-attachments/assets/74f217e6-82b8-40be-b605-f1b004bdc6b3)

In my opinion, **telegram stickers are very popular**, so it's important to be able to save them.

P. S. Your plugin is very useful, thank you!

**Comment by soberhacker** [comment]
Try this version:
https://t.me/obsidian_telegram_sync/65

However, note that Obsidian may not display all sticker files
