### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by cashew90** [soberhacker/obsidian-telegram-sync#61]
Hi there,

I did everything as explained, created a bot and entered the API key in the appropriate field in the settings. Despite, nothing is happening. Anything I can do about this? Thank you.

**Comment by ghedamat** [comment]
@cashew90 are you using the "append all to one file" option?

I'm finding that it doesn't seem to work, but posting to individual files does

**Comment by cashew90** [comment]
Yes, that's the culprit! I deactivated it and it started to work. But the issue persists when I activate it again.

**Comment by ghedamat** [comment]
quick debugging with dev tools shows that this line 

https://github.com/soberhacker/obsidian-telegram-sync/blob/main/src/main.ts#L60

is always false when the append option is on cc @soberhacker

**Comment by soberhacker** [comment]
@cashew90 @ghedamat Thank you guys for the feedback and help. Fixed

**Comment by soberhacker** [comment]
https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.1.0

**Comment by ghedamat** [comment]
thank you!
