### ISSUE TITLE
Insert channel/groups links

### ISSUE THREAD

**Issue by SamejSpenser** [soberhacker/obsidian-telegram-sync#62]
Hi @soberhacker, congratulations on the excellent plugin! 😉

I want to suggest the possibility of inserting the link of the forwarded message (when forwarded from a channel or group) to the note generated in Obsidian:

- **When “append all to one file” is _enabled_**, the message link can be embedded and/or added just below the sent content;

- **When “append all to one file” is _disabled_**, the message link can be inserted into the metadata;

Something like this:

**Append all to one file enabled:**

```
{{context}}

> [{{username}}]({{source}})
```

**Append all to one file disabled:**

```
---
create: "{{date:FORMAT}} • {{time:FORMAT}}"
tags: " TelegramSync xpto foo "
link: "{{source}}"
---

{{context}}
```

Where `{{username}}` would be something like `@durov` and `{{source}}` would be the direct link, `https://t.me/durov/134`, for example.

I already advance that I am NOT a programmer, and I don't know how to create a pull request for you to evaluate and/or implement, but I think it's a good addition to your splendid plugin! 😅

**Comment by soberhacker** [comment]
Hi @SamejSpenser. Thank you for your feedback and proposition. I decided that it is in context of my plugin, so have already added this feature. Use {{forwardFrom}} in your template to put link to original channel and original sender.
https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.1.0

**Comment by SamejSpenser** [comment]
Hi @soberhacker, thank you very much.

I'll test it right now. 😉

**Comment by SamejSpenser** [comment]
I tested it here using the variables in my template and the saved note was completely wrong.

When I capture without a template specified in the plugin settings, the note is created perfectly.

Here, the print of the Template:

![image](https://user-images.githubusercontent.com/14796034/235042517-ebc0ab47-f404-4cfe-8b23-9e80fb90c67e.png)

<p>&nbsp;</p>

Here, the prints with the Template enabled:

![image](https://user-images.githubusercontent.com/14796034/235042682-c4ccff45-d3c3-4b39-8f86-a6726c7340d4.png)

![image](https://user-images.githubusercontent.com/14796034/235042763-1de96b62-a986-423b-a43c-ea1636045c7c.png)

<p>&nbsp;</p>

Here, the prints with the Template disabled:

![image](https://user-images.githubusercontent.com/14796034/235042994-e46de7c9-6b12-48dc-9cc3-39f0b2f2a653.png)

![image](https://user-images.githubusercontent.com/14796034/235043051-a190419d-3b3b-48b4-ac39-580693d1b701.png)

<p>&nbsp;</p>

Here, the print of the message sent to the bot:

![image](https://user-images.githubusercontent.com/14796034/235043109-b2d33c5d-a71e-4402-ba88-05ea3e205ed8.png)

<p>&nbsp;</p>

Am I doing something wrong? Is there anything I can do here on my side to make it work properly? 🤔

**Comment by soberhacker** [comment]
Hi! Sorry, it is my mistake. I forgot to change description of parameter "Template File Location".
You should use {{content}} instead of {{conteXt}}. {{title}} is not supported (use Templater plugin for advanced templates)

Also in release https://github.com/soberhacker/obsidian-telegram-sync/releases/tag/1.1.1 
I fixed:
 - description of "Template File Location"
 - date format {{date:YYYYMMDD}}. Now you can set any date format (ex. YY-MM-DD)
 - time format {{time:HHmmss}}. Now you can set any time format (ex. HH:mm)
I added:
 - {{messageDate:FORMAT}} and {{messageTime:FORMAT}} to paste date and time of message creation in Telegram
 - {{date:FORMAT}} and {{time:FORMAT}} to paste date and time of note creation in Obsidian

**Comment by SamejSpenser** [comment]
Excellent!

I'll test it right now. 😉
