### ISSUE TITLE
Change repling with reacting("like") when marking message as processed

### ISSUE THREAD

**Issue by soberhacker** [soberhacker/obsidian-telegram-sync#74]

**Comment by knopki** [comment]
> Separate notes by folders, according to chats, topic-chats structure

More generic same theme feature request: ability to use template in file name. For example, allow set something like `inbox/telegram/{topicName}/{messageDate:YYYY}/{messageDate:MM}/{messageDate:YYYY-MM-DD} {messageTime:HH:mm} {content:30}` as file name template and save to something like `inbox/telegram/News/2023/05/2023-05-11 13:25 The war is over let's celebrat...md`

**Comment by knopki** [comment]
> two bots instance conflicts

My current solution to this: I use plugin `Plugin Groups` and enable `Telegram Sync` plugin only on one desktop machine.
An long term solution could be to save the "enable sync" setting to a non-syncable storage.

**Comment by soberhacker** [comment]
Done in 1.8.0
