### ISSUE TITLE
Possibility to use placeholder in Telegram.md

### ISSUE THREAD

**Issue by sirlaughalot90** [soberhacker/obsidian-telegram-sync#75]
Hi,

I have two feature requests which would be great to see being added:

1) A custom name for Telegram.md (e.g. Inbox).

2) A way to add placeholders ({{date}}, {{time}}) etc. to Telegram.md (or Inbox.md for that matter).

Cheers!

**Comment by burtasov** [comment]
Hi,

Give me a reason, please, why you need this feature. 
One of my main values is to not overload this plugin by not important settings. 

Thanks!

**Comment by soberhacker** [comment]
Hi,

Give me a reason, please, why you need this feature.
One of my main values is to not overload this plugin by not important settings.

Thanks!

**Comment by sirlaughalot90** [comment]
Sure thing; 1) Just aestethics. The file should serve as an inbox to me, and therefore also be called Inbox (or whatever you like). 2) Again, personal taste. It would make the plugin more useful to me if I could take only the functionality and implement it in the ways I want/need it. Dream scenario: A place holder for the content I send from Telegram (e.g. {{telegram}} which can be inserted in a template file. Probably a long shot but that would be ideal for my use case as I could implement it in my daily note for example. Next best thing: A customizable receiving note in Obsidian.

Cheers!

**Comment by cocoonkid** [comment]
Could the placeholder be the solution for #109  too?

**Comment by soberhacker** [comment]
> Could the placeholder be the solution for #109 too?

@cocoonkid I think, the solution is very simply - just skip handling message "/start"

**Comment by cocoonkid** [comment]
Agreed!  Still hoping for a placeholder so I can put some ascii  art instead of /start :)

**Comment by soberhacker** [comment]
Hi! I described how it will be done in file [Template Variables List](https://github.com/soberhacker/obsidian-telegram-sync/blob/main/docs/Template%20Variables%20List.md).
I think 3 or 4 weeks and it will be implemented.

**Comment by soberhacker** [comment]
Hi everyone, you can now test the new beta release [2.0.0-beta.1](https://t.me/obsidian_telegram_sync_insider/16).

You have two ways to install it:
1. Manually, using the link above from our Telegram channel.
2. Directly from the plugin settings, via a special button. This button is only available if you're connected to Telegram as a user and are using a plugin version greater than 1.10.0.

![image](https://github.com/soberhacker/obsidian-telegram-sync/assets/128756825/99afa579-888c-4e1d-ab3d-83e4407e3a44)

@sirlaughalot90 @cocoonkid

**Comment by soberhacker** [comment]
Release version 2.0.0 already published
